### ISSUE TITLE
CDATA sections not handled

### ISSUE THREAD

**Issue by onelesd** [mischov/meeseeks#11]
Has any thought been given to CDATA sections?

They seem to be ignored by all functions except `Meeseeks.html`, where further munging would be required to get the data.

Current behavior:
```
iex(1)> "<doc><c1><!-- CDATA[[1234]] --></c1></doc>" 
|> Meeseeks.parse 
|> Meeseeks.one(xpath "//c1") 
|> Meeseeks.text
""
iex(2)> "<doc><c1><!CDATA[[1234]]></c1></doc>" 
|> Meeseeks.parse 
|> Meeseeks.one(xpath "//c1") 
|> Meeseeks.text
""
```

Expected behavior:
```
iex(1)> "<doc><c1><!-- CDATA[[1234]] --></c1></doc>" 
|> Meeseeks.parse 
|> Meeseeks.one(xpath "//c1") 
|> Meeseeks.text
"1234"
```

**Comment by mischov** [comment]
@onelesd That is an interesting question.

The reason `Meeseeks.text` doesn't return anything for `<!-- CDATA[[1234]] -->` is because it's a comment, and generally speaking you don't want the text of comments to show up when you ask for a node's text.

Even if text worked, the contents of the comment node is `" CDATA[[1234]] "`, so it still wouldn't return just "1234".

I could see the use of providing a `cdata` extractor which would check a comment node and return the value if the node matches something like `^\sCDATA[[(.*)]]$`. 

Do you think that would meet your needs, or can you think of a cleaner solution?

**Comment by onelesd** [comment]
@mischov It is a comment, but it's also used frequently (inappropriately) on the webs so having a way to extract it easily would be nice.

I ended up doing this for this particular XML (it may not work with other-style CDATA comments):
```
  defp text_or_nil(result) do
    # handle CDATA
    case Meeseeks.tree result do
      {_, _, [{:comment, data}]} ->
        data
        |> String.trim_leading("[CDATA[")
        |> String.trim_trailing("]]")
      _ ->
        nil
    end
  end
```

**Comment by mischov** [comment]
That's pretty close to what I would do, except I would probably get the node from the document in the result and then use the nodes directly instead of building the tree.

Let me think about how I want to implement, but I agree with you that it would be good to have an easy extractor for CDATA and I'll see if I can't get that added soon.

Thank you for your feedback, please keep it coming. 😄

**Comment by mischov** [comment]
As of `v0.7.0`:

```elixir
iex> "<doc><c1><![CDATA[1234]]></c1></doc>"
|> Meeseeks.parse()
|> Meeseeks.one(xpath("//c1"))
|> Meeseeks.data()
"1234"
```

And if the source is an XML file you can now also do:

```elixir
iex> "<doc><c1><![CDATA[1234]]></c1></doc>"
|> Meeseeks.parse(:xml)
|> Meeseeks.one(xpath("//c1"))
|> Meeseeks.text()
"1234"
```
