### ISSUE TITLE
from Document to Document

### ISSUE THREAD

**Issue by cjen07** [mischov/meeseeks#19]
is there a way to generate a new document form part of nodes in an old document?

**Comment by mischov** [comment]
There is no direct path to achieve this, but you can select the nodes you're interested in, convert those results into html or a tuple-tree, and then parse that, generating a new document with only the data you're interested in.

It you need a better solution than that, please describe the use-case you have in mind in more detail and I can consider whether that is functionality I wish to add.

**Comment by cjen07** [comment]
when I got the selected nodes, how to convert them into html or tuple-tree?

**Comment by mischov** [comment]
If you're selecting through the normal channels (i.e. `Meeseeks.all`), it would look something like:

```elixir
Meeseeks.all(document, css("...")) |> Enum.map(&Meeseeks.tree/1)
# or
Meeseeks.all(document, css("...")) |> Enum.map(&Meeseeks.html/1) |> Enum.join(" ")
```

If you've somehow selected just nodes, it would look something like:

```elixir
Enum.map(nodes, &Meeseeks.Document.Node.tree(&1, document))
```

**Comment by cjen07** [comment]
does it look like this?
`b = get(url).body`
`document = Meeseeks.parse(b)`
`nodes = find_some_nodes(document.nodes)`
`Enum.map(nodes, &Meeseeks.Document.Node.tree(&1, document))`
it is not working

another question (my use case): 
https://gist.github.com/cjen07/61cd81262bb1d7b34a340e6aaee7123d

Thanks a lot!

**Comment by mischov** [comment]
Please expand upon "it is not working"- is it not working at all, or is it giving you a different result than you expect?

I will run your gist in the morning and will probably have a better answer then, but one possible answer is that `Meeseeks.text` joins text with a space, then collapses whitespace.

https://github.com/mischov/meeseeks/blob/master/lib/meeseeks/document/element.ex#L51-L55

Since it appears you are just doing a join of the content of the text nodes, this will give you a different result.

**Comment by cjen07** [comment]
The reason I want to convert part of a document to a new document is that I want to reuse selectors and combinators I coded. when `find_some_nodes` is simply `[document.nodes[1], domument.nodes[2]]`, there is an error: `** (FunctionClauseError) no function clause matching in Meeseeks.Document.Node.tree/2`

**Comment by mischov** [comment]
Well, not sure about the error you received there, but the error I receive when trying to do:

```elixir
b = get(url).body
document = Meeseeks.parse(b)
nodes = [document.nodes[1], document.nodes[2]]
Enum.map(nodes, &Meeseeks.Document.Node.tree(&1, document))
```

With the url from your gist is:

```
** (KeyError) key :type not found in: %{__struct__: Meeseeks.Document.Doctype, id: 1, name: "html", parent: nil, public: "", system: ""}
    (meeseeks) lib/meeseeks/document/doctype.ex:14: Meeseeks.Document.Doctype.tree/2
      (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
```

Which is a bug with how doctypes are parsed. (`Node.Doctype` expects a `:type` key but gets a `:name` key.) I will open a separate issue for and fix this problem.

In regards to the question raised by your gist, aside from what I already mentioned, your `run1` function does not preserve the order of the nodes, so `r1 != r2` because they're different paragraphs. I am not 100% sure why `run1` doesn't preserve the correct order but if you compare the results to the order of paragraphs in the original document you'll see that `r2` appears to follow that order while `r1` doesn't.

**Comment by cjen07** [comment]
yes, the point is node order in run1 is not preserved, so why is that? I have a difficulty in reading `Meeseek.all` and functions it is calling.

**Comment by mischov** [comment]
The short answer is, because I cheat. Node ids should be correctly ordered, so when I return my accumulator for `Accumulator.All` I order the results by node id. I also deduplicate by accumulating in a map of node id to result, before returning a list once I'm done walking- accumulating in a list like you do permits the chance of duplication.

https://github.com/mischov/meeseeks/blob/master/lib/meeseeks/accumulator/all.ex#L17

**Comment by cjen07** [comment]
Thanks very much! it is solved by just sorting the nodes by id before piping into the `Enum.reduce`

**Comment by mischov** [comment]
Oh- of course. `Map.values` doesn't maintain any kind of order.

**Comment by cjen07** [comment]
:grinning:

**Comment by mischov** [comment]
Please keep asking questions as you have them- it's led to one bug discovery already. :smiley:

**Comment by cjen07** [comment]
Sure :smiley:

**Comment by mischov** [comment]
Oh, and if you're trying to get a document's nodes in the correct order, try [`Meeseeks.Document.get_nodes/1`](https://hexdocs.pm/meeseeks/Meeseeks.Document.html#get_nodes/1) instead of `document.nodes |> Map.values() |> sorter()`.

**Comment by cjen07** [comment]
Oh yes, thanks!
