### ISSUE TITLE
Meeseeks without Rust

### ISSUE THREAD

**Issue by bidinzky** [mischov/meeseeks#21]
Hello,

if i only want a xml parser is there a posibility to remove the rust dependency?
I know that html is just xml-like and so i dont know if there are two different parsers or if there is one, but if there two can i drop the html one?
Really like your lib, but i am not allowed to install rust on a prod server :D.

sincerly
lukas

**Comment by mischov** [comment]
The XML parser also requires Rust (it uses xml5ever).

I would prefer to make the Rust dependency optional (it would lower the barrier for adoption and initial use of the library) and there are Elixir/Erlang XML parsers that I could adapt to work with Meeseeks, but I am hesitant to do so without being able to provide a safe, sane HTML parser (which doesn't exist in Elixir/Erlang).

I would also prefer to not have to provide a version of Meeseeks without any default parsers because I find it pretty user-unfriendly to require additional dependencies and configuration before a library can even be used.

I will think about the issue further, but in the meantime, you say that you cannot install Rust on a production server- is providing Rust on a build server an option? 

As I understand it, many Elixir deployments already create releases on a build server with similar architecture to the production server- if this is the case for you, you could compile Rust on your build server and avoid needing to install Rust on your production server.

**Comment by mischov** [comment]
I am very unlikely to drop support for html5ever.

If I was able to find a browser-grade HTML5 parser with a better getting-started story than needing to have Rust installed I might consider it as the *default* parser to reduce the friction of trying out Meeseeks, but it would need to be better in every way (speed, correctness, safety) for me to consider dropping html5ever support.

**Comment by mischov** [comment]
I am going to close this issue- for the moment Meeseeks is going to continue requiring Rust by default.

If somebody wants to work on creating non-Rust parsers, such as one using [MyHtml](https://github.com/lexborisov/myhtml) I am willing to help and otherwise give feedback, and potentially incorporate the result into Meeseeks if it makes sense and is desired.
