### ISSUE TITLE
Always crash when restart phx.server.

### ISSUE THREAD

**Issue by QwertyJack** [mischov/meeseeks#28]
I'm running a phx.server via systemd, which uses Meeseeks to deal with xpath, and my unit file looks like:
```
[Unit]
Description=phx hellow world

[Service]
ExecStart=/usr/local/bin/elixir --sname main --cookie 123 -S mix phx.server

[Install]
WantedBy=multi-user.target
```

Every time executing `sudo systemctl restart myapp.service` it generates a [erl_crash.dump](http://doscience.net/erl_crash.dump).

It seems that `Elixir.MeeseeksHtml5ever` crashed.

**Comment by mischov** [comment]
Is there any way you could provide a minimal test case (a git repo, probably) that I could work with?

**Comment by mischov** [comment]
@QwertyJack Also, does it work if you just use systemctl start? Is it the process of restarting that causes the problem?

Have you tried running the project without the dependency on Meeseeks to make sure it's actually Meeseeks causing the problem? I haven't even been able to get a bare-bones phoenix project (phx.new) to work with the above unit file so if there's more to your unit file or process that would be useful to know.

Finally, have you tried using systemd with a release rather than running `mix phx.server`?

**Comment by QwertyJack** [comment]
Thanks for your reply. I'll try later as soon as I can.

**Comment by QwertyJack** [comment]
Actually it crashes when stopping the service.

**Comment by mischov** [comment]
A minimal test case that would let me recreate the problem would be best.

I don't recognize the error and don't have enough information to even guess what it might be.

**Comment by QwertyJack** [comment]
I find that the crashes have nothing to do with Meeseeks -- even without any Meeseeks calls, it will generate crash file.
I'll change my systemd config to solve the crash.

Thank you anyway !
