### ISSUE TITLE
Add `Meeseeks.fetch_one` and `Meeseeks.fetch_all`?

### ISSUE THREAD

**Issue by mischov** [mischov/meeseeks#36]
On a recent issue @OvermindDL1 included a code snippet that contained:

```elixir
with(qt when qt != nil <- Meeseeks.one(doc, css(".qt"))) do
```

That struck me as clunky, but understandable because `Meeseeks.one` and `Meeseeks.all` don't really provide a good interface for use inside of `with`.

To help remedy this situation I'm considering adding `Meeseeks.fetch_one` and `Meeseeks.fetch_all`, which would return something along the lines of `{:ok, %Result{}} | :error` and `{:ok, [%Result{}]} | :error` respectively. Is there interest in this?

A further point to consider is whether they should just return `:error` when there's no matches, which is the Elixir standard for `fetch` functions, or if they should return some custom error / value which would be easier to match on in the `else` clause of a `with`.

Thoughts?

**Comment by Eiji7** [comment]
@mischov In my opinion it should be `{:error, :no_match}` (or similar), because:

1. `{:ok, result} | {:error, reason}` are most popular in designing libraries, so it's easier for new `Elixir` developers
2. To prevent soon API break in future versions
For example in other version you could add support for `{:error, :invalid_document}` (when someone will pass wrong variable). In such case semantic version requires to change major version number.
3. To work easier with other libraries
For example: https://github.com/CrowdHailer/OK#ok-pipeline-operator
```
import OK, only: [~>>: 2]

get_document()
~>> Meeseeks.one(css(".example"))
~>> do_something()
```

**Comment by OvermindDL1** [comment]
> Is there interest in this?

Yes, and this is the erlang (elixir'y) way as well, a return 'should' be entirely distinguishable via matchers without needing guards.  :-)

But yes, the success case should always be `:ok` or `{:ok, value}` depending on whether it has a value or not and the failure case should always be `:error` or `{:error, reason}` if a reason is at all returnable (it almost always is, so the 2-tuple should generally be used).

The whole `term() | nil` return type is not at all 'beamy' for really any language on the beam other than a couple of really broken Elixir API's (notable in Enum because they copied some ruby mis-designs I'm guessing).  ^.^

**Comment by mischov** [comment]
> The whole term() | nil return type is not at all 'beamy' for really any language on the beam other than a couple of really broken Elixir API's

Ecto, which originally inspired the `all`/`one` syntax, is another.

Meeseeks was one of my first Elixir projects and there is a lot about the API choices that I'd probably do different now but that I'm hesitant to break backward compatibility to change.

The whole API is very influenced by my coming from Clojure, which often over-uses/propagates `nil`, and from trying to support easy piping, where instead I'm more likely to reach for `with` these days.

**Comment by OvermindDL1** [comment]
> Ecto, which originally inspired the all/one syntax, is another.

Ecto is also more ruby'ish than Beam'ish though, so not a great example...  ^.^;

> Meeseeks was one of my first Elixir projects and there is a lot about the API choices that I'd probably do differently now but that I'm hesitant to break backward compatibility to change.

Yeah that's the big thing about a lot of the Elixir ecosystem.  Many came from Ruby or so and not Erlang and thus did not know 'why' Erlang made certain decisions, or even that it did at all, so tend to be re-learning the same things.  :-)

> The whole API is very influenced by my coming from Clojure, which often over-uses/propagates nil, and from trying to support easy piping, where instead I'm more likely to reach for with these days.

Clojure is not a language I've learned yet, but I could see that doing that as well.

Overall thoguh, `{:ok, value}`/`{:error, reason}` are easier to pipe with many libraries (like the above listed `ok` library or expede's exceptional or even Elixir's built-in `with`) because with these you don't need to worry about the 'error case'/`nil` propagating into functions that it does not necessarily belong in, which is what causes a lot of horrors like:
```elixir
blah
|> something()
|> bloop()
|> case do
  nil -> nil
  value -> more_things(value)
end
|> etc...
```
Which was why Elixir added `with`.  :-)

**Comment by mischov** [comment]
I wonder if it would be worth it to make a big, breaking update to the API so that it's more Elixir-y, and what that API might look like if I did?

I **do not** like to make breaking changes, particularly across a whole API. Another option would be to add more Elixir-y functions alongside the existing API functions (for instance, adding `fetch_one` and `fetch_all`), but I worry about the API becoming overlarge and confusing.

**Comment by OvermindDL1** [comment]
> I wonder if it would be worth it to make a big, breaking update to the API so that it's more Elixir-y, and what that API might look like if I did?

As long as it's documented and the major version number increments then it's safe.  :-)

> I do not like to make breaking changes, particularly across a whole API. Another option would be to add more Elixir-y functions alongside the existing API functions (for instance, adding fetch_one and fetch_all), but I worry about the API becoming overlarge and confusing.

True, on both counts...

**Comment by jwarlander** [comment]
In general, I like the availability of all three options á la `Map`;
- `Map.get(map, key, default)` for getting either an existing value, or a default
- `Map.fetch(map, key)` for getting an `{:ok, value}` or `:error` / `{:error, reason}` that I can handle as needed
- `Map.fetch!(map, key)` for "give me a value, or else..!"

It allows me as a user of a library to determine what I need in my particular situation.

Thus.. I'm all for adding `Meeseeks.fetch_one` and `Meeseeks.fetch_all` as proposed :) No need to break existing API, as that approach can *also* be useful depending on the context.
