### ISSUE TITLE
Parsing some nodes text returns HTML tags instead of text

### ISSUE THREAD

**Issue by sztosz** [mischov/meeseeks#47]
```
x = "<div class=\"adaptive\"><noscript data-src-small=\"http://filmyfantastyczne.pl/wp-content/uploads/2018/07/karta-cinema-city-unlimited-monolith-films-kino-188x144.jpg\" data-src-medium=\"http://filmyfantastyczne.pl/wp-content/uploads/2018/07/karta-cinema-city-unlimited-monolith-films-kino-188x144.jpg\" data-src-high=\"http://filmyfantastyczne.pl/wp-content/uploads/2018/07/karta-cinema-city-unlimited-monolith-films-kino-94x72.jpg\" data-src-x-high=\"http://filmyfantastyczne.pl/wp-content/uploads/2018/07/karta-cinema-city-unlimited-monolith-films-kino-188x144.jpg\" data-width=\"94\" data-height=\"72\" data-alt=\"karta-cinema-city-unlimited-monolith-films-kino\"> <img src=\"http://filmyfantastyczne.pl/wp-content/uploads/2018/07/karta-cinema-city-unlimited-monolith-films-kino-188x144.jpg\" alt=\"\" width=\"188\" height=\"144\"> </noscript></div>"

result = Meeseeks.one(x, css("div"))
Meeseeks.text(result)
```
returns `"<img src=\"http://filmyfantastyczne.pl/wp-content/uploads/2018/07/karta-cinema-city-unlimited-monolith-films-kino-188x144.jpg\" alt=\"\" width=\"188\" height=\"144\">"`

And IMHO should return `""`

Is this a bug or expected behaviour?

**Comment by mischov** [comment]
Thank you for your report.

> Is this a bug or expected behaviour?

That's a good question: I think it might be a bug but I'll need to investigate to be sure.

**Comment by mischov** [comment]
@sztosz Woo, what a can of worms.

1. This behavior is due to html5ever's parsing behavior, though that parsing behavior is due in part to the fact that `meeseeks_html5ever` uses the default html5ever tree-builder opts, which marks `scripting_enabled` to true and will impact how `<noscript>` elements are rendered.

2. I'm not sure I'd expect `<noscript>` to be rendered the way it is being rendered by html5ever when reading [the appropriate portion of HTML5 spec](https://html.spec.whatwg.org/multipage/scripting.html#the-noscript-element), but I might just be misunderstanding the spec.

   If you create a `.html` file with the example content and open it in either Chrome or Firefox then inspect the element, you will find that the "<img...>" bit is rendered as a text-node in both, so html5ever's behavior seems to be inline with what browsers do.

**Comment by sztosz** [comment]
@mischov I saved this example to html file, and opened it in Firefox. With JS enabled i saw nothing. Blank page, no text, no nothing (same with vivaldi, don't have chrome installed here). With JS disabled I saw correctly rendered image. And when I manipulated width and height of the <img> tag the image was properly stretched. 

But back to JS enabled. I sadly don't fully understand the `"<img...>" bit is rendered as a text-node` part. If it's rendered as text-node why I don't see text? What am I missing?

**Comment by mischov** [comment]
@sztosz Open your inspect tab (F12), look at the elements, and dig down. It's a part of the DOM, just not a visible one.

**Comment by sztosz** [comment]
@mischov Ok, but if it's part of DOM, why isn't it rendered. Or maybe I'm asking wrong question... is there or will there be way to use html5ever with scripting disabled? Or maybe yet another question, is there a way to get what is displayed to the user in browser like it didn't load any JS or CSS? ;)

**Comment by sztosz** [comment]
Ok, I fully understand your reasoning. I'll try to mix Meeseeks with https://github.com/rrrene/html_sanitize_ex. If you are are ok with status quo, and I see no reason why you should not, I think you can close this issue :)

**Comment by mischov** [comment]
@sztosz You should open an issue on meeseeks_html5ever about allowing `TreeBuilderOpts` to be provided to html5ever.

I'll go ahead and close this issue.
