### ISSUE TITLE
Heroku build instructions in README don't appear to work currently

### ISSUE THREAD

**Issue by ohi-admin** [mischov/meeseeks#49]
This isn't a meeseeks issue, per se, other than the README's steps for how to build on Heroku don't appear to work. I've made an issue on heroku-buildpack-rust: https://github.com/emk/heroku-buildpack-rust/issues/37

If you've successfully gotten this to work, any feedback is appreciated! If I'm able to figure it out, I'll post back here with the solution.

**Comment by mischov** [comment]
@ohi-admin I haven't built Heroku for quite a while, and when trying what worked for me before (which is in-line with the instructions in the README, though not 100% the same) I encounter the same error as yourself.

Like you I'm not finding cargo in the `/app/tmp/cache/` when looking for it with `ls` in a hook in the Elixir buildpack, so I used a buildpack to run shell scripts between the Rust and Elixir buildpacks, and this is what I saw:

```
remote: -----> Skipping Cargo build
remote: -----> Niteoweb Shell app detected
remote: -----> Running .heroku/run.sh
remote: total 16
remote: drwx------ 4 u15147 dyno 4096 Dec 11 21:04 .
remote: drwx------ 4 u15147 dyno 4096 Dec 11 21:03 ..
remote: drwx------ 3 u15147 dyno 4096 Dec 11 21:04 cargo
remote: drwx------ 6 u15147 dyno 4096 Dec 11 21:03 multirust
remote: cargo 1.31.0 (339d9f9c8 2018-11-16)
```

But then in Elixir buildpack it's:

```
remote: -----> Executing hook before fetching app dependencies: ls -la /app/tmp/cache/
remote: total 62376
remote: drwx------ 3 u15147 dyno     4096 Dec 11 21:04 .
remote: drwx------ 4 u15147 dyno     4096 Dec 11 21:03 ..
remote: -rw------- 1 u15147 dyno  4946583 Dec 11 21:04 elixir-v1.6.4.zip
remote: drwx------ 8 u15147 dyno     4096 Dec 11 21:04 erlang
remote: -rw------- 1 u15147 dyno 58905616 Dec 11 21:04 OTP-20.3.tar.gz
remote: -rw------- 1 u15147 dyno       10 Dec 11 21:04 stack
```

And since I'm seeing this:

```
remote: -----> Stack changed, will rebuild
```

That means that this code is being called as part of the Elixir buildpack: 

```
    output_section "Stack changed, will rebuild"
    rm -rf ${cache_path}/*
```

Which is probably why `cargo` is gone. Not sure how to fix.

**Comment by pwightman** [comment]
Ah. Interesting. This was happening on the initial deploy, previous to any stack existing...I commented out the code requiring Meeseeks and removed the dependency, deployed successfully, then added back the dependency and it worked fine. So sounds like the bug lies with the Elixir buildpack. I'll file an issue there. Thanks so much for tracking that down!

**Comment by mischov** [comment]
If you run this somehow before you get to the Elixir build pack, it'll build fine, but I don't know what implication doing so might otherwise have

```
mkdir -p $2

cache_path=$(cd $2 && pwd)

if [ ! -f "${cache_path}/stack" ] ; then
    echo "${STACK}" > "${cache_path}/stack"
fi
```

**Comment by anulman** [comment]
Ha! I wrote those instructions, and just got bit by this same issue while upgrading to heroku-18.

@ohi-admin, @pwightman, and future travelers: if the buildpack has not been updated upstream, please check out this fork: https://github.com/chefconnie/heroku-buildpack-elixir

**Comment by axelson** [comment]
@anulman can you create a PR with those changes to https://github.com/HashNuke/heroku-buildpack-elixir ?

**Comment by anulman** [comment]
See https://github.com/HashNuke/heroku-buildpack-elixir/pull/146

If your desired OTP version is not covered or you have trouble building on heroku-18, try this upstream PR as well: https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/pull/65

**Comment by axelson** [comment]
Sorry, didn't recognize that PR as related to this issue from the title 😅, but the good news is that it works! (not using heroku-18 so not trying out #65 yet)

**Comment by mischov** [comment]
Should be resolved again as of: https://github.com/HashNuke/heroku-buildpack-elixir/pull/160.

Closing.
