### ISSUE TITLE
 Panicked with Utf8Error when trying to parse Google result 

### ISSUE THREAD

**Issue by raooll** [mischov/meeseeks#50]
iex(27)> html = HTTPoison.get!("https://www.google.com/search?q=wild%20love&start=0&gws_rd=cr&gbv=1").body 

iex(22)> s = Meeseeks.parse(html, :xml)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 35017, error_len: Some(1) }', libcore/result.rs:1009:5
                                                                                                                                                            {:error,
 "called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 35017, error_len: Some(1) }"}

Getting the above error while parsing  a google search page.

**Comment by raooll** [comment]
Can someone please help .

**Comment by mischov** [comment]
Firstly, you should use the html parser (`Meeseeks.parse(html, :html)`, or just `parse/1`) for html, not the xml parser.

Secondly, if you were to look at the request you get back from `HTTPoison.get!` you'd see that the content type being returned is `text/html; charset=ISO-8859-1`. Because the charset is ISO-8859-1, unicode parse errors occur.

Google returns content in ISO-8859-1 when you don't provide a user agent it likes, which Hackney won't. The following works.

```
iex> html = HTTPoison.get!("https://www.google.com/search?q=wild%20love&start=0&gws_rd=cr&gbv=1", ["User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"]).body
"..."
iex> s = Meeseeks.parse(html)                                                                   
#Meeseeks.Document<{...}>  
```

**Comment by raooll** [comment]
@mischov thanks a lot .
