### ISSUE TITLE
CSS selector id with tilde in name

### ISSUE THREAD

**Issue by Xeronel** [mischov/meeseeks#58]
There is a website I am parsing that included ~ as a prefix to many of it's ids. I'm unable to use css() in order to select them.

```
Meeseeks.one(~S(<div id="~testing"></div>), css("div#~testing"))  

** (Meeseeks.Error) 

  Type: :css_selector_tokenizer

  Reason: :invalid_input

  Metadata:
    input: "div#~testing"
    leex_reason: {:illegal, '#~'}
    (meeseeks) lib/meeseeks/selector/css/tokenizer.ex:17: Meeseeks.Selector.CSS.Tokenizer.tokenize/1
    (meeseeks) lib/meeseeks/selector/css.ex:9: Meeseeks.Selector.CSS.compile_selectors/1
    (meeseeks) expanding macro: Meeseeks.CSS.css/1
    iex:32: (file)
```

**Comment by OvermindDL1** [comment]
According to the HTML spec itself the `~` character is not a valid id character, so that site should be pretty hard failing validation.

However, CSS has a way to select non-conforming fields like that, and that is to use an attribute selector instead of the id selector, so instead of something like `div#~testing` I'd imagine something like `div[id="~testing"]` should work instead, so probably just changing your `css("div#~testing")` into `css("div[\"~testing\"]")` or so.

But yeah, `~` is **not** a valid character for an ID according to the HTML spec.

**Comment by mischov** [comment]
Specifically, an id in CSS may be:

```
-?{nmstart}{nmchar}*
```

Which is made up of

```
h		[0-9a-f]
nonascii	[\240-\377]
unicode		\\{h}{1,6}(\r\n|[ \t\r\n\f])?
escape		{unicode}|\\[^\r\n\f0-9a-f]
nmstart		[_a-z]|{nonascii}|{escape}
nmchar		[_a-z0-9-]|{nonascii}|{escape}
```

The CSS lexer for Meeseeks isn't that permissive, which I should probably look into improving, but for the moment @OvermindDL1's suggestion works.

```elixir
iex(1)> import Meeseeks.CSS
Meeseeks.CSS

iex(2)> html = ~S(<div id="~testing"></div>)
"<div id=\"~testing\"></div>"

iex(3)> Meeseeks.one(html, css("div[id=\"~testing\"]"))
#Meeseeks.Result<{ <div id="~testing"></div> }>

```

**Comment by OvermindDL1** [comment]
As I recall, `~` is specifically not allowed in id fields because it (among others) are selectors in CSS, thus allowing `~` in CSS can become ambiguous.  You can of course perform both types of CSS tests when it exists to get all possible results, but that would not be following the spec.  CSS already has ways to select non-conforming tags so I personally wouldn't think the CSS selector should be made any more permissive as that would then add ambiguity.

**Comment by mischov** [comment]
Also, in HTML5 [what an id can contain](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute) got a lot more permissive:

> When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character. The value must not contain any ASCII whitespace.
>
> The id attribute specifies its element's unique identifier (ID).
> 
> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.
>
> An element's unique identifier can be used for a variety of purposes, most notably as a way to link to specific parts of a document using fragments, as a way to target an element when scripting, and as a way to style a specific element from CSS.

**Comment by OvermindDL1** [comment]
True, but for CSS selectors you don't want ambiguity, that's why it is less permissive in the spec and why attribute selectors are recommended for such ID's.

**Comment by mischov** [comment]
So while `div#~testing` isn't a valid selector, a legitimate way to write it would be `div#\~testing`.

Meeseeks currently doesn't support escaped characters like that in names, idents, or strings, but doing so is in-line with the [CSS Grammar](https://www.w3.org/TR/CSS21/grammar.html#scanner) so I am going to update Meeseeks to correctly handle escapes.

While I'm at it, I'll add support for Elixir unicode code points in names, idents, and strings, though I'm going to punt on supporting hexadecimal Unicode code points for the moment.

**Comment by OvermindDL1** [comment]
Ahh, I didn't know about escaping CSS chars, thanks for that!

**Comment by mischov** [comment]
I'm going to leave this open until there is a release containing #59.

**Comment by mischov** [comment]
Support for escaped characters (and Elixir-style unicode code points) in CSS selector names, idents, and strings has been added in v0.11.2.

```elixir
iex(1)> import Meeseeks.CSS
Meeseeks.CSS

iex(2)> Meeseeks.one("<div id=\"~\"></div>", css("#\\~"))
#Meeseeks.Result<{ <div id="~"></div> }>

iex(3)> Meeseeks.one("<div class=\"❤\"></div>", css(".❤"))  
#Meeseeks.Result<{ <div class="❤"></div> }>
```
