### ISSUE TITLE
Sanitization, serialization, and minification

### ISSUE THREAD

**Issue by alizain** [mischov/meeseeks#80]
Hey @mischov - I made and have been using in production a library called `semtex` for HTML sanitization, serialization, escaping, and basic minification. It also uses `html5ever` for parsing :)

I think adding some of these features to `meeseeks` may be a better option than keeping it as a standalone library. If you're interested, I'd be happy to talk about it some more and to implement it!

https://github.com/alizain/semtex

**Comment by mischov** [comment]
@alizain Thank you for the idea- I will look into what Semtex does then get back to you.

**Comment by alizain** [comment]
I will warn you that there is zero documentation

**Comment by mischov** [comment]
Not a problem. :slightly_smiling_face: 

You definitely do a much more thorough job sanitizing!

**Comment by alizain** [comment]
> You definitely do a much more thorough job escaping!

After looking through `meeseeks` some more, that and escaping feel like the most important things to bring over. Serialization and stripping of whitespace seem to be mostly there

**Comment by mischov** [comment]
Well, the whitespace stripping is mostly a `text` and `data` thing, and doesn't apply to HTML serialization via `html`.

Setting aside `parse_fragment` for the moment, it would certainly be possible to create an extractor in the model of [`Meeseeks.Extractor.Html`](https://github.com/mischov/meeseeks/blob/87966445d979f4de19d1e0a19e5596990d4d301e/lib/meeseeks/extractor/html.ex) that would serialize a document or node to HTML, optionally sanitizing and minifying along the way.

In fact, the approach laid out in `Meeseeks.Extractor.Html` wouldn't even require that extractor to be part of Meeseeks itself. One could simply define a library that provided such an extractor, parse with Meeseeks, then extract with the extractor from the library. 

More thorough escaping is definitely something I'd be willing to consider adding to the existing `html` extractor, but I am not sure minification or sanitization belong there. 

I would probably suggest first implementing such an extractor as a separate library, and then bringing it into Meeseeks if there were a lot of people who felt it would be better as part of the core library. Doing so would also make it easier to iterate the development of that extractor on a separate cycle than Meeseek's, which probably makes sense because it has a whole library's worth of complexity as it is. :slightly_smiling_face: 

I would be willing to advise if you were interested in implementing such an extractor as a separate library.

**Comment by alizain** [comment]
> Well, the whitespace stripping is mostly a `text` and `data` thing, and doesn't apply to HTML serialization via `html`

Whitespace in HTML, especially extra newlines, do impact how the browser renders inline elements.

> it would certainly be possible to create an extractor in the model of Meeseeks.Extractor.Html that would serialize a document or node to HTML, optionally sanitizing and minifying along the way.

Something I don't understand right now - most functions in `Result`, `Node`, and some in `Document` simply call the correct method from `Extractors` and sometimes do whitespace fixing. Why is the API this way? Why not simply offer a single way to extract stuff: through the `Extractors` - with all logic related to whitespace in there?

> I would be willing to advise if you were interested in implementing such an extractor as a separate library.

Hmm... a separate library somewhat defeats the purpose for me. `semtex` is doing a great job of sanitization already, and I'm using it in production. The underlying purpose of getting that code into `meeseeks` is to get more eyes/usage on it to find bugs.

**Comment by alizain** [comment]
Also, sanitization doesn't feel like the job of an Extractor.

Extractors seem to have this signature:
```
document -> string || number
```

Sanitization will _always_ have the following signature:
```
document -> document
```

It's a transformation pass that's independent of rendering/extracting

**Comment by mischov** [comment]
> Whitespace in HTML, especially extra newlines, do impact how the browser renders inline elements.

In *Meeseeks* the extractors that collapse whitespace are `text` and `data` extractors, not the `html` extractor. So it doesn't do what you're looking for. That's all I was trying to communicate.

> Something I don't understand right now - most functions in Result, Node, and some in Document simply call the correct method from Extractors and sometimes do whitespace fixing.

Short answer is historical reasons and backwards compatibility, but another reason is that extractors are about getting some information out of nodes, and that you can call them with a result or document is incidental so rather than pollute the logic of extraction with incidental information about how unwrap other ways nodes might be presented (results or documents) those live in the appropriate namespace. 

Not convinced this is the best organization, but don't see any reason to break backwards compatibility around it now.

**Comment by mischov** [comment]
>Extractors seem to have this signature:
>
> `document -> string || number`

No, extractors don't have any common signature and they're not really a formalized concept. At the highest level extractors are just a way to extract some kind of data from HTML data, whether that data is represented by a `Result`, or a `Document`, or a `Node`. 

`Meeseeks.Extractor` extractors focus on the details of getting information out of nodes, but they're then wrapped by `Meeseeks.Document.Node`, or `Meeseeks.Document`, or `Meeseeks.Result` to handle additional logic that is required for each of those types.

I agree that the `Meeseeks.Extractor` extractors could return values more consistent with what the various wrappers return- the main reason they don't currently is because a lot of things return strings and I don't want to convert iodata to a string before absolutely necessary. This is something I'm still trying to balance right.

> Sanitization will always have the following signature:
>
> `document -> document`

As an abstract concept this is probably correct. But if what you're looking for is the modification of a document, that's not offered by Meeseeks. Meeseeks is currently entirely focused on querying and extracting data, not updating documents, and document modification is not a can of worms I want to open right now.

In practice, in your public usage of Semtex I believe you always serialize after sanitation, so an extractor that extracts from a document to a sanitized string of HTML is consistent with how I've observed you use Semtex, and would be consistent with how Meeseeks currently works.

I understand that there isn't much of a compelling reason to create a separate library (other than being able to use an Elixir wrapper of `html5ever` that gets updated more regularly than `html5ever_elixir`) when you already have a working solution as a library, but it benefits Meeseeks more for it to stabilize and mature separately before potentially being brought in at some point.

**Comment by mischov** [comment]
I'm going to close this for now but feel free to re-open or start a new issue if you need more clarification on something or want to pursue the idea as a separate library.
